In [1]:
import pandas as pd

In [2]:
dict1 = {'Name':['priyang', 'aadhya', 'krisha', 'vedant', 'parshv', 'mittal', 'archana'],
         'Marks': [98,89,99,87,90,83,99],
         'Gender': ['Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female']
        }

In [3]:
df1 = pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  priyang     98    Male
1   aadhya     89  Female
2   krisha     99  Female
3   vedant     87    Male
4   parshv     90    Male
5   mittal     83  Female
6  archana     99  Female

In [4]:
# 1 display to 3 rows of the dataset
df1.head(3)

      Name  Marks  Gender
0  priyang     98    Male
1   aadhya     89  Female
2   krisha     99  Female

In [5]:
# 2 display bottom 3 rows of the dataset
df1.tail(3)

      Name  Marks  Gender
4   parshv     90    Male
5   mittal     83  Female
6  archana     99  Female

In [6]:
# 3 find shape of our dataset
df1.shape

(7, 3)

In [7]:
print('number of rows', df1.shape[0])
print('number of columns', df1.shape[1])

number of rows 7
number of columns 3

In [8]:
# 4 get information about our dataset like total number rows, total number of columns, datatypes of each columns and memory requirement
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [9]:
# 5 chceck null values in the dataset
df1.isnull()

    Name  Marks  Gender
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4  False  False   False
5  False  False   False
6  False  False   False

In [10]:
df1.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

In [11]:
df1.isnull().sum(axis=1)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [12]:
# 6 get overall statistics about the dataframe
df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [13]:
df1.describe(include ='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

In [14]:
# 7 find unique values from the gender column
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [15]:
# 8 find the number of unique values from the gender column
df1['Gender'].nunique()

2

In [16]:
# 9 display count of unique values in gender column
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

In [17]:
# 10 find total number of students having marks between 90 to 100 (inclusive) using between method
df1['Marks']>=90

0     True
1    False
2     True
3    False
4     True
5    False
6     True
Name: Marks, dtype: bool

In [18]:
df1[df1['Marks']>=90]

      Name  Marks  Gender
0  priyang     98    Male
2   krisha     99  Female
4   parshv     90    Male
6  archana     99  Female

In [19]:
len(df1[(df1['Marks']>=90) & (df1['Marks']<=100)])

4

In [20]:
df1['Marks'].between(90,100)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
Name: Marks, dtype: bool

In [21]:
sum(df1['Marks'].between(90,100))

4

In [22]:
# 11 find average marks
df1['Marks'].mean() # min , max

np.float64(92.14285714285714)

In [23]:
#12 apply method
def marks(x) :
    return x//2

In [24]:
df1['Marks'].apply(marks)

0    49
1    44
2    49
3    43
4    45
5    41
6    49
Name: Marks, dtype: int64

In [25]:
df1['Half_marks'] = df1['Marks'].apply(marks) # added new column

In [26]:
df1

      Name  Marks  Gender  Half_marks
0  priyang     98    Male          49
1   aadhya     89  Female          44
2   krisha     99  Female          49
3   vedant     87    Male          43
4   parshv     90    Male          45
5   mittal     83  Female          41
6  archana     99  Female          49

In [27]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

In [28]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [29]:
#13 map function
# we want to convert male in 1 and female in 0
df1['Gender'].map({'Male':1,'Female':0})

0    1
1    0
2    0
3    1
4    1
5    0
6    0
Name: Gender, dtype: int64

In [30]:
df1['Male_Female'] = df1['Gender'].map({'Male':1, 'Female':0}) # added new column

In [31]:
df1

      Name  Marks  Gender  Half_marks  Male_Female
0  priyang     98    Male          49            1
1   aadhya     89  Female          44            0
2   krisha     99  Female          49            0
3   vedant     87    Male          43            1
4   parshv     90    Male          45            1
5   mittal     83  Female          41            0
6  archana     99  Female          49            0

In [36]:
# 14 drop the columns
df1.drop('Male_Female', axis = 1) # for 1 column
df1.drop(['Male_Female', 'Half_marks'], axis = 1, inplace = True) # for multiple columns

In [38]:
df1

      Name  Marks  Gender
0  priyang     98    Male
1   aadhya     89  Female
2   krisha     99  Female
3   vedant     87    Male
4   parshv     90    Male
5   mittal     83  Female
6  archana     99  Female

In [39]:
# 15 print name of the columns
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [40]:
df1.index

RangeIndex(start=0, stop=7, step=1)

In [42]:
# 16 sort the dataframe as per the marks columns
df1.sort_values(by = 'Marks')

      Name  Marks  Gender
5   mittal     83  Female
3   vedant     87    Male
1   aadhya     89  Female
4   parshv     90    Male
0  priyang     98    Male
2   krisha     99  Female
6  archana     99  Female

In [43]:
df1.sort_values(by = 'Marks', ascending = False)

      Name  Marks  Gender
2   krisha     99  Female
6  archana     99  Female
0  priyang     98    Male
4   parshv     90    Male
1   aadhya     89  Female
3   vedant     87    Male
5   mittal     83  Female

In [45]:
df1.sort_values(by = [ 'Marks', 'Gender'], ascending = False)

      Name  Marks  Gender
2   krisha     99  Female
6  archana     99  Female
0  priyang     98    Male
4   parshv     90    Male
1   aadhya     89  Female
3   vedant     87    Male
5   mittal     83  Female

In [46]:
# 17 display name and marks of the female students
df1['Gender']

0      Male
1    Female
2    Female
3      Male
4      Male
5    Female
6    Female
Name: Gender, dtype: object

In [47]:
df1[df1['Gender'] == 'Female']

      Name  Marks  Gender
1   aadhya     89  Female
2   krisha     99  Female
5   mittal     83  Female
6  archana     99  Female

In [48]:
df1[df1['Gender'] == 'Female'][['Name','Marks']]

      Name  Marks
1   aadhya     89
2   krisha     99
5   mittal     83
6  archana     99

In [49]:
df1['Gender'].isin(['Female'])

0    False
1     True
2     True
3    False
4    False
5     True
6     True
Name: Gender, dtype: bool

In [50]:
df1[df1['Gender'].isin(['Female'])]

      Name  Marks  Gender
1   aadhya     89  Female
2   krisha     99  Female
5   mittal     83  Female
6  archana     99  Female

In [51]:
df1[df1['Gender'].isin(['Female'])] [['Name','Marks']]

      Name  Marks
1   aadhya     89
2   krisha     99
5   mittal     83
6  archana     99