In [1]:
# download data set

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('C:/Users/nachiket/Downloads/archive/Salaries.csv')

C:\Users\nachiket\AppData\Local\Temp\ipykernel_8556\3165964340.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('C:/Users/nachiket/Downloads/archive/Salaries.csv')

In [4]:
# display top rows of the dataset
data.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [5]:
# check last 10 rows of the dataset
data.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [6]:
# Find shape of our dataset (number of rows and number of columns)
data.shape

(148654, 13)

In [7]:
print("number of rows", data.shape[0])
print("number of columns", data.shape[1])

number of rows 148654
number of columns 13

In [8]:
# Getting information about our dataset like total number rows
# Total number of columns, datatypes of each column and memory requirement
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [9]:
# Check null values in the dataset
data.isnull()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,False,False,False,False,False,False,False,False,False,False,True,False,False
148650,False,False,False,False,False,False,False,False,False,False,True,False,True
148651,False,False,False,False,False,False,False,False,False,False,True,False,True
148652,False,False,False,False,False,False,False,False,False,False,True,False,True
148653,False,False,False,False,False,False,False,False,False,False,True,False,False

In [10]:
data.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [11]:
#  Drop ID, notes, agency and status columns
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [12]:
data = data.drop(['Id','Notes','Agency','Status'],axis = 1)

In [13]:
data.head(1)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011

In [14]:
# Get overall statistics about the dataframe

In [15]:
data.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [16]:
data.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

In [17]:
# Find occurrence of the employee names (top 5)

In [18]:
data['EmployeeName'].value_counts()

EmployeeName
Kevin Lee                 13
William Wong              11
Richard Lee               11
Steven Lee                11
John Chan                  9
                          ..
Saoirse C Brownfield       1
Miguel P Lucana            1
Johnmark L Henderson       1
Laura R Epstein-Norris     1
Kesha Mcwhorter            1
Name: count, Length: 110811, dtype: int64

In [19]:
data['EmployeeName'].value_counts().head()

EmployeeName
Kevin Lee       13
William Wong    11
Richard Lee     11
Steven Lee      11
John Chan        9
Name: count, dtype: int64

In [20]:
# Find the number of unique job titles

In [21]:
data['JobTitle'].nunique()

2159

In [22]:
# Total number of job titles contain captain

In [23]:
data['JobTitle']

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object

In [24]:
data['JobTitle'].str.contains('CAPTAIN')

0         False
1          True
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: JobTitle, Length: 148654, dtype: bool

In [25]:
data[data['JobTitle'].str.contains('CAPTAIN')]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.0,87082.62,110804.3,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
8684,JEANNE SEYLER,"CAPTAIN, FIRE SUPPRESSION",95055.34,0.0,9197.14,NaN,104252.48,104252.48,2011
10485,JANE SMITH,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",74592.0,1538.59,18804.68,NaN,94935.27,94935.27,2011
11198,KATHRYN BROWN,CAPTAIN III (POLICE DEPARTMENT),10684.5,0.0,81244.87,NaN,91929.37,91929.37,2011
31297,MARCO CARNIGLIA,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",9839.72,0.0,1203.77,NaN,11043.49,11043.49,2011
34124,JOHN FORBES-3,"CAPTAIN, FIRE SUPPRESSION",0.0,982.06,2277.34,NaN,3259.40,3259.40,2011

In [26]:
len(data[data['JobTitle'].str.contains('CAPTAIN')])

141

In [27]:
len(data[data['JobTitle'].str.contains('CAPTAIN', case = False)])

552

In [28]:
data[data['JobTitle'].str.contains('CAPTAIN')].count()

EmployeeName        141
JobTitle            141
BasePay             141
OvertimePay         141
OtherPay            141
Benefits              0
TotalPay            141
TotalPayBenefits    141
Year                141
dtype: int64

In [29]:
data[data['JobTitle'].str.contains('CAPTAIN', case = False)].count()

EmployeeName        552
JobTitle            552
BasePay             551
OvertimePay         552
OtherPay            552
Benefits            411
TotalPay            552
TotalPayBenefits    552
Year                552
dtype: int64

In [30]:
# Display all the employee names from fire department

In [31]:
data[data['JobTitle'].str.contains('fire', case = False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
6,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011
8,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011
9,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011
10,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.9,NaN,299494.17,299494.17,2011
...,...,...,...,...,...,...,...,...,...
145956,Kenneth C Farris,Firefighter,0.00,0.00,0.00,4645.56,0.00,4645.56,2014
147556,Edward A Dunn,Firefighter,1063.24,0.00,132.90,385.66,1196.14,1581.80,2014
148021,Kari A Johnson,Firefighter,688.71,0.00,0.00,143.39,688.71,832.10,2014
148209,Sheryl K Lee,Firefighter,459.14,0.00,0.00,95.59,459.14,554.73,2014
148554,Lawrence F Gatt,Fire Alarm Dispatcher,73.33,0.00,0.00,0.73,73.33,74.06,2014

In [32]:
data[data['JobTitle'].str.contains('fire', case = False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

In [33]:
# Find minimum, maximum and average basepay

In [34]:
data['BasePay'].describe()

count     148049.0
unique    109900.0
top            0.0
freq         875.0
Name: BasePay, dtype: float64

In [35]:
# Replace 'not provided' in employeename column to NaN

In [36]:
data['EmployeeName']

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650         Not provided
148651         Not provided
148652         Not provided
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [37]:
import numpy as np
data['EmployeeName'] = data['EmployeeName'].replace('Not provided', np.nan)

In [38]:
data['EmployeeName']

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [39]:
# Drop the rows having 5 missing values

In [40]:
data.isnull().sum()

EmployeeName            4
JobTitle                0
BasePay               605
OvertimePay             0
OtherPay                0
Benefits            36159
TotalPay                0
TotalPayBenefits        0
Year                    0
dtype: int64

In [41]:
# Keep only rows that have fewer than 5 missing values
data[data.isnull().sum(axis=1) >= 5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

In [42]:
data.drop(data[data.isnull().sum(axis=1)==5].index, axis = 0)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,NaN,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,NaN,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,NaN,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [43]:
data.drop(data[data.isnull().sum(axis=1)==5].index, axis = 0, inplace = True)

In [44]:
data.isnull().sum(axis=1)

0         1
1         1
2         1
3         1
4         1
         ..
148649    0
148650    1
148651    1
148652    1
148653    0
Length: 148654, dtype: int64

In [45]:
# find job title of ALBERT PARDINI

In [46]:
data[data['EmployeeName']=='ALBERT PARDINI']

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [47]:
data[data['EmployeeName']=='ALBERT PARDINI']['JobTitle']

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

In [48]:
# how much albert pardini make (include benefits)?

In [49]:
data[data['EmployeeName']=='ALBERT PARDINI']['TotalPayBenefits']

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [50]:
# Display name of the person having the highest basepay
# 1. Convert BasePay to numbers (strings become NaN)
data['BasePay'] = pd.to_numeric(data['BasePay'], errors='coerce')

In [51]:
data[data['BasePay'].max() == data['BasePay']]['EmployeeName']

72925    Gregory P Suhr
Name: EmployeeName, dtype: object

In [52]:
data[data['BasePay'].max() == data['BasePay']]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
72925,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013

In [53]:
# find average basepay of all employee per jobTitle

In [ ]:
# 2. Now run your groupby
result = data.groupby('Year')['BasePay'].mean()

print(result)

In [ ]:
# find average basepay of employee having job title accountant

In [ ]:
data[data['JobTitle']=='ACCOUNTANT']

In [ ]:
data[data['JobTitle']=='ACCOUNTANT']['BasePay'].mean()

In [ ]:
# find top 5 most common jobs

In [ ]:
data['JobTitle'].value_counts().head()